/* AUTO-GENERATED by npm run sync:gallery — do not edit by hand */
import React from 'react';
import {AbsoluteFill, staticFile, useCurrentFrame} from 'remotion';
import {schema as schema_post_103, DURATION as duration_post_103} from '../templates/post-103/schema';
import {SoftFloatCard as Card_post_103} from '../templates/post-103/presets/soft-float';
import {schema as schema_post_111, DURATION as duration_post_111} from '../templates/post-111/schema';
import {SoftFloatCard as Card_post_111} from '../templates/post-111/presets/soft-float';
import {schema as schema_post_126, DURATION as duration_post_126} from '../templates/post-126/schema';
import {SoftFloatCard as Card_post_126} from '../templates/post-126/presets/soft-float';
import {schema as schema_post_130, DURATION as duration_post_130} from '../templates/post-130/schema';
import {SoftFloatCard as Card_post_130} from '../templates/post-130/presets/soft-float';
import {schema as schema_post_1, DURATION as duration_post_1} from '../templates/post-1/schema';
import {SoftFloatCard as Card_post_1} from '../templates/post-1/presets/soft-float';
import {schema as schema_post_58, DURATION as duration_post_58} from '../templates/post-58/schema';
import {SoftFloatCard as Card_post_58} from '../templates/post-58/presets/soft-float';
import {schema as schema_post_91, DURATION as duration_post_91} from '../templates/post-91/schema';
import {SoftFloatCard as Card_post_91} from '../templates/post-91/presets/soft-float';
import {schema as schema_post_pomogote, DURATION as duration_post_pomogote} from '../templates/post-pomogote/schema';
import {SoftFloatCard as Card_post_pomogote} from '../templates/post-pomogote/presets/soft-float';
import {schema as schema_post_zadolbalo_shablon, DURATION as duration_post_zadolbalo_shablon} from '../templates/post-zadolbalo-shablon/schema';
import {SoftFloatCard as Card_post_zadolbalo_shablon} from '../templates/post-zadolbalo-shablon/presets/soft-float';

function makeComposition(Card: React.ComponentType<any>, segmentFrames: number) {
  const Wrapped: React.FC<Record<string, unknown>> = (props) => {
    const frame = useCurrentFrame();
    const image = typeof props.image === 'string' ? props.image : 'generated/post-126.png';
    return (
      <AbsoluteFill style={{alignItems: 'center', justifyContent: 'center', background: '#c8ccd0'}}>
        <Card
          card={props}
          localFrame={frame}
          segmentFrames={segmentFrames}
          imageSrc={staticFile(image)}
        />
      </AbsoluteFill>
    );
  };
  return Wrapped;
}

export const GALLERY_COMPOSITIONS = [
  {
    id: 'Post103Css',
    duration: duration_post_103,
    schema: schema_post_103,
    defaultProps: {
          "image": "generated/post-126.png",
          "background": "#D9DDE0",
          "body": "Group 1",
          "body2": "helloiam am",
          "body3": "Group 2",
          "body4": "Say Hello to Armenian Wine"
    },
    Component: makeComposition(Card_post_103, duration_post_103),
  },
  {
    id: 'Post111Css',
    duration: duration_post_111,
    schema: schema_post_111,
    defaultProps: {
          "image": "generated/post-91-hero.png",
          "background": "#0F0F10",
          "title": "HELLO\nI AM\nAM\nMEANS\nARMENIA",
          "titleColor": "#FFFFFF"
    },
    Component: makeComposition(Card_post_111, duration_post_111),
  },
  {
    id: 'Post126SoftFloat',
    duration: duration_post_126,
    schema: schema_post_126,
    defaultProps: {
          "title": "Hello, WORLD",
          "quote": "Armenia welcomed 172,705 international visitors in April 2026",
          "label": "AM NEWS",
          "image": "generated/post-126.png",
          "background": "#D9DDE0",
          "titleColor": "#0F0F10",
          "quoteColor": "#D61E23",
          "labelColor": "#4A7BFF"
    },
    Component: makeComposition(Card_post_126, duration_post_126),
  },
  {
    id: 'Post130Css',
    duration: duration_post_130,
    schema: schema_post_130,
    defaultProps: {
          "image": "generated/post-126.png",
          "background": "#D9DDE0",
          "quote": "Travel platforms and international media increasingly describe Armenia as Europe’s next rising tourism star. Visitors are drawn by the country’s mix of ancient history, dramatic landscapes, Soviet-modernist aesthetics and famously overwhelming hospitality. Unfortunately for tourists, “light local dinner” in Armenia still translates to approximately 14 dishes, emotional toasts and a grandmother personally monitoring whether you finished your food.",
          "quoteColor": "#0F0F10",
          "label": "AM NEWS",
          "labelColor": "#4A7BFF",
          "title": "Hello, WORLD",
          "titleColor": "#0F0F10"
    },
    Component: makeComposition(Card_post_130, duration_post_130),
  },
  {
    id: 'Post1Css',
    duration: duration_post_1,
    schema: schema_post_1,
    defaultProps: {
          "image": "generated/post-91-hero.png",
          "background": "#D9DDE0",
          "body": "Zadolbalo Shablon",
          "title": "HELLO\nI AM\nAM\nMEANS\nARMENIA",
          "titleColor": "#FFFFFF"
    },
    Component: makeComposition(Card_post_1, duration_post_1),
  },
  {
    id: 'Post58LavashIntro',
    duration: duration_post_58,
    schema: schema_post_58,
    defaultProps: {
          "title": "Hello, I Am\nLAVASH",
          "label": "AM FOOD",
          "image": "generated/post-126.png",
          "background": "#D9DDE0",
          "titleColor": "#0F0F10",
          "labelColor": "#000000"
    },
    Component: makeComposition(Card_post_58, duration_post_58),
  },
  {
    id: 'Post91Css',
    duration: duration_post_91,
    schema: schema_post_91,
    defaultProps: {
          "image": "generated/post-91-hero.png",
          "background": "#0F0F10",
          "title": "HELLO\nI AM\nAM\nMEANS\nARMENIA",
          "titleColor": "#FFFFFF"
    },
    Component: makeComposition(Card_post_91, duration_post_91),
  },
  {
    id: 'PostpomogoteCss',
    duration: duration_post_pomogote,
    schema: schema_post_pomogote,
    defaultProps: {
          "image": "generated/post-126.png",
          "background": "#D9DDE0",
          "quote": "Armenia welcomed 172,705 international visitors in April 2026",
          "quoteColor": "#D61E23",
          "label": "AM NEWS",
          "labelColor": "#4A7BFF",
          "title": "Hello, WORLD",
          "titleColor": "#0F0F10"
    },
    Component: makeComposition(Card_post_pomogote, duration_post_pomogote),
  },
  {
    id: 'PostzadolbaloshablonCss',
    duration: duration_post_zadolbalo_shablon,
    schema: schema_post_zadolbalo_shablon,
    defaultProps: {
          "image": "generated/zadolbalo-hero.png",
          "background": "#0F0F10",
          "title": "HELLO\nI AM\nAM\nMEANS\nARMENIA",
          "titleColor": "#FFFFFF"
    },
    Component: makeComposition(Card_post_zadolbalo_shablon, duration_post_zadolbalo_shablon),
  }
] as const;
