/* AUTO-GENERATED by npm run sync:gallery — do not edit by hand */
import React from 'react';
import {AbsoluteFill, staticFile, useCurrentFrame} from 'remotion';
import {schema as schema_rubric_card, DURATION as duration_rubric_card} from '../templates/rubric-card/schema';
import {SoftFloatCard as Card_rubric_card} from '../templates/rubric-card/presets/soft-float';

function makeComposition(Card: React.ComponentType<any>, segmentFrames: number) {
  const Wrapped: React.FC<Record<string, unknown>> = (props) => {
    const frame = useCurrentFrame();
    const image = typeof props.image === 'string' ? props.image : 'generated/helloiam-lavash.png';
    return (
      <AbsoluteFill style={{alignItems: 'center', justifyContent: 'center', background: '#c8ccd0'}}>
        <Card
          card={props}
          localFrame={frame}
          segmentFrames={segmentFrames}
          imageSrc={staticFile(image)}
        />
      </AbsoluteFill>
    );
  };
  return Wrapped;
}

export const GALLERY_COMPOSITIONS = [
  {
    id: 'RubricCardCss',
    duration: duration_rubric_card,
    schema: schema_rubric_card,
    defaultProps: {
          "engine": "green-plate",
          "cardKind": "hello",
          "cardIndex": 0,
          "cardCount": 3,
          "title": "HELLO, I AM",
          "titleAccent": "FOOD",
          "label": "AM FOOD",
          "background": "#D9DDE0",
          "titleColor": "#0F0F10",
          "accentColor": "#D61E23",
          "labelColor": "#000000",
          "image": "generated/helloiam-lavash.png",
          "introLayout": "lavash"
    },
    Component: makeComposition(Card_rubric_card, duration_rubric_card),
  }
] as const;
