/* AUTO-GENERATED by npm run sync:gallery — do not edit by hand */
import React from 'react';
import {AbsoluteFill, useCurrentFrame} from 'remotion';
import {resolveImageSrc} from '../templates/_shared/resolve-image-src';
import {schema as schema_post_103, DURATION as duration_post_103} from '../templates/post-103/schema';
import {SoftFloatCard as Card_post_103} from '../templates/post-103/presets/soft-float';
import {schema as schema_post_104, DURATION as duration_post_104} from '../templates/post-104/schema';
import {SoftFloatCard as Card_post_104} from '../templates/post-104/presets/soft-float';
import {schema as schema_post_112, DURATION as duration_post_112} from '../templates/post-112/schema';
import {SoftFloatCard as Card_post_112} from '../templates/post-112/presets/soft-float';
import {schema as schema_post_5, DURATION as duration_post_5} from '../templates/post-5/schema';
import {SoftFloatCard as Card_post_5} from '../templates/post-5/presets/soft-float';
import {schema as schema_post_70, DURATION as duration_post_70} from '../templates/post-70/schema';
import {SoftFloatCard as Card_post_70} from '../templates/post-70/presets/soft-float';
import {schema as schema_post_82, DURATION as duration_post_82} from '../templates/post-82/schema';
import {SoftFloatCard as Card_post_82} from '../templates/post-82/presets/soft-float';
import {schema as schema_post_88, DURATION as duration_post_88} from '../templates/post-88/schema';
import {SoftFloatCard as Card_post_88} from '../templates/post-88/presets/soft-float';
import {schema as schema_post_89, DURATION as duration_post_89} from '../templates/post-89/schema';
import {SoftFloatCard as Card_post_89} from '../templates/post-89/presets/soft-float';
import {schema as schema_post_91, DURATION as duration_post_91} from '../templates/post-91/schema';
import {SoftFloatCard as Card_post_91} from '../templates/post-91/presets/soft-float';
import {schema as schema_post_94, DURATION as duration_post_94} from '../templates/post-94/schema';
import {SoftFloatCard as Card_post_94} from '../templates/post-94/presets/soft-float';
import {schema as schema_post_95, DURATION as duration_post_95} from '../templates/post-95/schema';
import {SoftFloatCard as Card_post_95} from '../templates/post-95/presets/soft-float';
import {schema as schema_post_96, DURATION as duration_post_96} from '../templates/post-96/schema';
import {SoftFloatCard as Card_post_96} from '../templates/post-96/presets/soft-float';
import {schema as schema_post_97, DURATION as duration_post_97} from '../templates/post-97/schema';
import {SoftFloatCard as Card_post_97} from '../templates/post-97/presets/soft-float';
import {schema as schema_post_98, DURATION as duration_post_98} from '../templates/post-98/schema';
import {SoftFloatCard as Card_post_98} from '../templates/post-98/presets/soft-float';
import {schema as schema_post_99, DURATION as duration_post_99} from '../templates/post-99/schema';
import {SoftFloatCard as Card_post_99} from '../templates/post-99/presets/soft-float';
import {schema as schema_rubric_card, DURATION as duration_rubric_card} from '../templates/rubric-card/schema';
import {SoftFloatCard as Card_rubric_card} from '../templates/rubric-card/presets/soft-float';

function makeComposition(Card: React.ComponentType<any>, segmentFrames: number) {
  const Wrapped: React.FC<Record<string, unknown>> = (props) => {
    const frame = useCurrentFrame();
    const imageSrc = resolveImageSrc(props.image);
    return (
      <AbsoluteFill style={{alignItems: 'center', justifyContent: 'center', background: '#c8ccd0'}}>
        <Card
          card={props}
          localFrame={frame}
          segmentFrames={segmentFrames}
          imageSrc={imageSrc}
        />
      </AbsoluteFill>
    );
  };
  return Wrapped;
}

export const GALLERY_COMPOSITIONS = [
  {
    id: 'Post103Css',
    duration: duration_post_103,
    schema: schema_post_103,
    defaultProps: {
          "background": "#D9DDE0",
          "body2": "helloiam am",
          "body2Color": "#420000",
          "body4": "Say Hello\nto Armenian Wine",
          "body4Color": "#420000",
          "image": "generated/helloiam-wine-armenia.png"
    },
    Component: makeComposition(Card_post_103, duration_post_103),
  },
  {
    id: 'Post104Css',
    duration: duration_post_104,
    schema: schema_post_104,
    defaultProps: {
          "background": "#D9DDE0",
          "image": "generated/helloiam-wine-armenia.png"
    },
    Component: makeComposition(Card_post_104, duration_post_104),
  },
  {
    id: 'Post112Css',
    duration: duration_post_112,
    schema: schema_post_112,
    defaultProps: {
          "background": "#FFC53A",
          "body2": "helloiam am",
          "body2Color": "#0F0F10",
          "image": ""
    },
    Component: makeComposition(Card_post_112, duration_post_112),
  },
  {
    id: 'Post5Css',
    duration: duration_post_5,
    schema: schema_post_5,
    defaultProps: {
          "background": "#FFC53A",
          "title": "HELLO,\nI AM\nDZIRANI",
          "titleColor": "#0F0F10",
          "label": "AM FOOD",
          "labelColor": "#000000",
          "image": ""
    },
    Component: makeComposition(Card_post_5, duration_post_5),
  },
  {
    id: 'Post70Css',
    duration: duration_post_70,
    schema: schema_post_70,
    defaultProps: {
          "background": "#D61E23",
          "title": "HELLO,\nI AM\nGREEN\nPLATE",
          "titleColor": "#FFFFFF",
          "label": "AM FOOD",
          "labelColor": "#000000",
          "image": "generated/helloiam-lavash.png"
    },
    Component: makeComposition(Card_post_70, duration_post_70),
  },
  {
    id: 'Post82Css',
    duration: duration_post_82,
    schema: schema_post_82,
    defaultProps: {
          "background": "#D9DDE0",
          "title": "HELLO\nI AM\nAM\nMEANS\nARMENIA",
          "titleColor": "#4A7BFF"
    },
    Component: makeComposition(Card_post_82, duration_post_82),
  },
  {
    id: 'Post88Css',
    duration: duration_post_88,
    schema: schema_post_88,
    defaultProps: {
          "background": "#D61E23",
          "title": "AM\nMEANS",
          "titleColor": "#FFC53A"
    },
    Component: makeComposition(Card_post_88, duration_post_88),
  },
  {
    id: 'Post89Css',
    duration: duration_post_89,
    schema: schema_post_89,
    defaultProps: {
          "background": "#000000",
          "title": "HELLO\nI AM\nAM\nMEANS\nARMENIA",
          "titleColor": "#FFC53A",
          "image": "generated/image-79-1.png"
    },
    Component: makeComposition(Card_post_89, duration_post_89),
  },
  {
    id: 'Post91Css',
    duration: duration_post_91,
    schema: schema_post_91,
    defaultProps: {
          "background": "#0F0F10",
          "title": "HELLO\nI AM\nAM\nMEANS\nARMENIA",
          "titleColor": "#FFFFFF",
          "image": "generated/image-79-1.png"
    },
    Component: makeComposition(Card_post_91, duration_post_91),
  },
  {
    id: 'Post94Css',
    duration: duration_post_94,
    schema: schema_post_94,
    defaultProps: {
          "background": "#FFC53A",
          "title": "HELLO\nI AM",
          "titleColor": "#0F0F10"
    },
    Component: makeComposition(Card_post_94, duration_post_94),
  },
  {
    id: 'Post95Css',
    duration: duration_post_95,
    schema: schema_post_95,
    defaultProps: {
          "background": "#000000",
          "title": "HELLO\nI AM\nAM",
          "titleColor": "#FFFFFF",
          "image": "generated/image-79-1.png"
    },
    Component: makeComposition(Card_post_95, duration_post_95),
  },
  {
    id: 'Post96Css',
    duration: duration_post_96,
    schema: schema_post_96,
    defaultProps: {
          "background": "#000000",
          "title": "AM MEANS\nARMENIA",
          "titleColor": "#FFC53A",
          "image": "generated/image-79-1.png"
    },
    Component: makeComposition(Card_post_96, duration_post_96),
  },
  {
    id: 'Post97Css',
    duration: duration_post_97,
    schema: schema_post_97,
    defaultProps: {
          "background": "#000000",
          "title": "HELLO\nI AM\nAM\nMEANS\nARMENIA",
          "titleColor": "#D61E23",
          "image": "generated/image-79-1.png"
    },
    Component: makeComposition(Card_post_97, duration_post_97),
  },
  {
    id: 'Post98Css',
    duration: duration_post_98,
    schema: schema_post_98,
    defaultProps: {
          "background": "#000000",
          "title": "HELLO\nI AM\nAM\nMEANS\nARMENIA",
          "titleColor": "#D61E23",
          "image": "generated/image-79-1.png"
    },
    Component: makeComposition(Card_post_98, duration_post_98),
  },
  {
    id: 'Post99Css',
    duration: duration_post_99,
    schema: schema_post_99,
    defaultProps: {
          "background": "#D79689",
          "body2": "helloiam am",
          "body2Color": "#0F0F10",
          "image": "generated/helloiam-lavash.png"
    },
    Component: makeComposition(Card_post_99, duration_post_99),
  },
  {
    id: 'RubricCardCss',
    duration: duration_rubric_card,
    schema: schema_rubric_card,
    defaultProps: {
          "engine": "green-plate",
          "cardKind": "hello",
          "cardIndex": 0,
          "cardCount": 3,
          "title": "HELLO, I AM",
          "titleAccent": "FOOD",
          "label": "AM FOOD",
          "background": "#D9DDE0",
          "titleColor": "#0F0F10",
          "accentColor": "#D61E23",
          "labelColor": "#000000",
          "image": "generated/helloiam-lavash.png",
          "introLayout": "lavash"
    },
    Component: makeComposition(Card_rubric_card, duration_rubric_card),
  }
] as const;
