import {readdir, readFile, writeFile} from 'node:fs/promises';
import path from 'node:path';

const SKIP_DIRS = new Set(['_shared', '_generated']);

/** @param {string} layoutTs */
function parseLayoutTs(layoutTs) {
  const body = layoutTs
    .replace(/^import[^\n]+\n/, '')
    .replace(/export const LAYOUT: LayoutSpec = /, '')
    .trim()
    .replace(/;\s*$/, '');
  return Function(`"use strict"; return (${body})`)();
}

/** @param {string} studioRoot */
export async function syncPreviewLayouts(studioRoot) {
  const templatesRoot = path.join(studioRoot, 'src', 'templates');
  const galleryDir = path.join(studioRoot, 'src', 'gallery');
  const entries = await readdir(templatesRoot, {withFileTypes: true});
  const layouts = {};

  for (const entry of entries) {
    if (!entry.isDirectory() || SKIP_DIRS.has(entry.name) || entry.name.startsWith('_')) continue;
    const metaPath = path.join(templatesRoot, entry.name, 'meta.json');
    const layoutPath = path.join(templatesRoot, entry.name, 'layout.ts');
    try {
      const meta = JSON.parse(await readFile(metaPath, 'utf8'));
      const layoutTs = await readFile(layoutPath, 'utf8');
      layouts[meta.id] = parseLayoutTs(layoutTs);
    } catch {
      // skip
    }
  }

  await writeFile(
    path.join(galleryDir, 'preview-layouts.json'),
    `${JSON.stringify(layouts, null, 2)}\n`,
  );
  return {count: Object.keys(layouts).length};
}

/** @param {string} studioRoot */
export async function syncGalleryManifest(studioRoot) {
  const templatesRoot = path.join(studioRoot, 'src', 'templates');
  const galleryDir = path.join(studioRoot, 'src', 'gallery');
  const entries = await readdir(templatesRoot, {withFileTypes: true});

  const metas = [];
  for (const entry of entries) {
    if (!entry.isDirectory() || SKIP_DIRS.has(entry.name) || entry.name.startsWith('_')) continue;
    const metaPath = path.join(templatesRoot, entry.name, 'meta.json');
    try {
      const raw = await readFile(metaPath, 'utf8');
      metas.push({dir: entry.name, ...JSON.parse(raw)});
    } catch {
      // skip dirs without meta
    }
  }

  metas.sort((a, b) => a.id.localeCompare(b.id));

  const imports = metas
    .map(
      (m) =>
        `import {schema as schema_${m.dir.replace(/-/g, '_')}, DURATION as duration_${m.dir.replace(/-/g, '_')}} from '../templates/${m.dir}/schema';
import {SoftFloatCard as Card_${m.dir.replace(/-/g, '_')}} from '../templates/${m.dir}/presets/soft-float';`,
    )
    .join('\n');

  const compositions = metas
    .map((m) => {
      const d = m.dir.replace(/-/g, '_');
      return `  {
    id: '${m.id}',
    duration: duration_${d},
    schema: schema_${d},
    defaultProps: ${JSON.stringify(m.defaultProps ?? {}, null, 6).replace(/\n/g, '\n    ')},
    Component: makeComposition(Card_${d}, duration_${d}),
  }`;
    })
    .join(',\n');

  const manifestTs = `/* AUTO-GENERATED by npm run sync:gallery — do not edit by hand */
import React from 'react';
import {AbsoluteFill, useCurrentFrame} from 'remotion';
import {resolveImageSrc} from '../templates/_shared/resolve-image-src';
${imports}

function makeComposition(Card: React.ComponentType<any>, segmentFrames: number) {
  const Wrapped: React.FC<Record<string, unknown>> = (props) => {
    const frame = useCurrentFrame();
    const imageSrc = resolveImageSrc(props.image);
    return (
      <AbsoluteFill style={{alignItems: 'center', justifyContent: 'center', background: '#c8ccd0'}}>
        <Card
          card={props}
          localFrame={frame}
          segmentFrames={segmentFrames}
          imageSrc={imageSrc}
        />
      </AbsoluteFill>
    );
  };
  return Wrapped;
}

export const GALLERY_COMPOSITIONS = [
${compositions}
] as const;
`;

  await writeFile(path.join(galleryDir, 'composition-manifest.tsx'), manifestTs);
  await syncPreviewLayouts(studioRoot);

  return {count: metas.length, ids: metas.map((m) => m.id)};
}
